routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout','HomeController@logout');
Route::group(['middleware'=> ['admin']],function(){
    Route::get('/admin/dashboard', 'AdminController@index')->name('admin');
    // Route::resource('/home', 'HomePageController');
    Route::resource('/aboutus', 'AboutUsController');
    Route::resource('/services', 'ServicesController');
    // Route::resource('/contact', 'AboutUsController');
});

app/AboutUs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AboutUs extends Model
{
    //
}

app/Http/Controllers/AboutUsController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\AboutUs;

class AboutUsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = AboutUs::orderby('created_at','desc')->get();
        return view('admin.about-us.index',compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.about-us.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'subtitle' => 'required',
            'content' => 'required',
            'image' => 'required|image'
        ]);

        // dd($request->all());
        $post = new AboutUs;

        $post_image = $request->image;
        $post_image_new_name = time() . $post_image->getClientOriginalName();
        $post_image->move('uploads/about-us', $post_image_new_name);

        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->content = $request->content;
        $post->image = 'uploads/about-us/' . $post_image_new_name;

        $post->save();
        toastr()->success('Data has been saved successfully!');
        return redirect()->back();
        // 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $about = AboutUs::findOrFail($id);
        return view('admin.about-us.edit',compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[

        ]);
            $post = AboutUs::findOrFail($id);

        if($request->hasFile('image'))
        {
            $post_image = $request->image;

            $post_image_new_name = time() . $post_image->getClientOriginalName();

            $post_image->move('uploads/about-us', $post_image_new_name);

            $post->image = 'uploads/about-us/' . $post_image_new_name;

            $post->save();
        }

        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->content = $request->content;

        $post->save();
        toastr()->success('Data has been Updated successfully!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $about = AboutUs::findOrFail($id);

        if(file_exists($about->image))
        {
            unlink($about->image);
        }

        $about->delete();

        toastr()->success('Data has been Deleted successfully!');
        return redirect()->back();
    }
}

resources/views/admin/about-us/create.blade.php
@extends('admin.layout.master')
@push('plugin-styles')
    <link rel="stylesheet" href="{{ asset('/assets/plugins/simplemde/simplemde.min.css') }}">
@endpush

@section('content')
<nav class="page-breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/aboutus">About Us</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add contents</li>
  </ol>
</nav>

<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Create contents</h4>
        {{-- @if($errors->any())
            <ul class="list-group ">
                @foreach ($errors->all() as $error)
                    <li class="list-group-item alert-fill-danger mb-2" role="alert">
                        {{ $error }}
                    </li>
                @endforeach
            </ul>
         @endif --}}
        <form action="{{ route('aboutus.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label>Title</label>
                <input type="text"  class="form-control @error('title') is-invalid @enderror" name="title" autocomplete="off" placeholder="Title" value="{{ old('title') }}">
                @error('title')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
              </div>
              <div class="form-group">
              <label>Sub Title</label>
              <input type="text" class="form-control @error('subtitle') is-invalid @enderror"  name="subtitle" autocomplete="off" placeholder="Sub Title" value="{{ old('subtitle') }}">
              @error('subtitle')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </div>
            <textarea class="form-control @error('content') is-invalid @enderror" name="content" id="tinymceExample" rows="10" >
                {{ old('content') }}
                @error('content')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
              @enderror
            </textarea>
            <div class="form-group">
                <label>Image</label>
                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" autocomplete="off" value="{{ old('image') }}">
                @error('image')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
              </div>

              <button class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>
    
@endsection
@push('plugin-scripts')
<script src="{{ asset('/assets/plugins/tinymce/tinymce.min.js') }}"></script>
@endpush

@push('custom-scripts')
<script src="{{ asset('/assets/js/tinymce.js') }}"></script>
@endpush

resources/views/admin/about-us/edit.blade.php
@extends('admin.layout.master')
@push('plugin-styles')
    <link rel="stylesheet" href="{{ asset('/assets/plugins/simplemde/simplemde.min.css') }}">
@endpush
@section('content')
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/aboutus">About Us</a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit contents</li>
    </ol>
  </nav>
  
  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Create contents</h4>
          <form action="{{ route('aboutus.update',$about->id) }}" method="POST" enctype="multipart/form-data">
              @csrf
              @method('PUT')
              <div class="form-group">
                  <label>Title</label>`
                  <input type="text"  class="form-control @error('title') is-invalid @enderror" name="title" autocomplete="off" placeholder="Title" value="{{ $about->title }}">
                  @error('title')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror
                </div>
                <div class="form-group">
                <label>Sub Title</label>
                <input type="text" class="form-control @error('subtitle') is-invalid @enderror"  name="subtitle" autocomplete="off" placeholder="Sub Title" value="{{ $about->subtitle}}">
                @error('subtitle')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </div>
              <textarea class="form-control @error('content') is-invalid @enderror" name="content" id="tinymceExample" rows="10" >
                  {{ $about->content }}
                  @error('content')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
                @enderror
              </textarea>
              <div class="form-group">
                  <label>Image</label>
                  <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" autocomplete="off" value="{{ $about->image }}">
                  @error('image')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror
                </div>
  
                <button class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
      
  @endsection
  @push('plugin-scripts')
  <script src="{{ asset('/assets/plugins/tinymce/tinymce.min.js') }}"></script>
  @endpush
  
  @push('custom-scripts')
  <script src="{{ asset('/assets/js/tinymce.js') }}"></script>
  @endpush

resources/views/admin/about-us/index.blade.php
@extends('admin.layout.master')
@section('content')
@push('plugin-styles')
<link rel="stylesheet" href="{{ asset('/assets/plugins/datatables-net/dataTables.bootstrap4.css') }}">
@endpush
<a href="{{route('aboutus.create')}}" class="btn btn-primary mb-4">Create Contents</a>
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Admin Dashboard</a></li>
      <li class="breadcrumb-item active" aria-current="page">About Us</li>
    </ol>
  </nav>
  
  <div class="row">
    <div class="col-md-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h6 class="card-title">About Us</h6>
          <div class="table-responsive">
            <table id="dataTableExample" class="table">
              <thead>
                <tr>
                  <th>Image</th>
                  <th>Title</th>
                  <th>Sub Title</th>
                  <th>Contents</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($abouts as $about)
                <tr>
                  <td><img src="{{ asset($about->image) }}" alt=""></td>
                  <td>{{ $about->title }}</td>
                  <td>{{ $about->subtitle }}</td>
                  <td>{!! $about->content !!}</td>
                  <td>
                    <a href="{{route('aboutus.edit',$about->id)}}" class="btn btn-info btn-sm ">Edit</a>
                    <form action="{{route('aboutus.destroy',$about->id)}}" method="post" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger btn-sm">delete</button>
                    </form> 
                    {{-- <a href="" class="btn btn-danger btn-sm">Delete</a> --}}
                    <a href="" class="btn btn-primary btn-sm">View</a>
                 </td>
                </tr>
                  @endforeach
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('custom-scripts')
<script src="{{ asset('/assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('/assets/js/data-table.js') }}"></script>
@endpush

@push('plugin-scripts')

<script src="{{ asset('/assets/plugins/datatables-net/jquery.dataTables.js') }}" defer></script>
<script src="{{ asset('/assets/plugins/datatables-net-bs4/dataTables.bootstrap4.js') }}" defer></script>

@endpush